apiVersion: v1
kind: Service
metadata:
  name: {{ include "local.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "local.name" . }}
    helm.sh/chart: {{ include "local.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "local.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
